# Generated by Django 5.0.2 on 2025-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='icono',
            field=models.CharField(default='fas fa-circle', help_text='Clase de Font Awesome para el icono (ej: fas fa-check-circle)', max_length=50),
        ),
    ]
