# Generated by Django 5.0.2 on 2025-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_estado_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Color en formato hexadecimal (ej: #28a745 para verde)', max_length=7),
        ),
    ]
