# Generated by Django 5.0.2 on 2025-06-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_estado_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='tipo',
            field=models.CharField(choices=[('edificio', 'Edificio'), ('sala', 'Sala'), ('oficina', 'Oficina'), ('bodega', 'Bodega')], max_length=20),
        ),
    ]
