# Generated by Django 5.0.2 on 2025-06-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_ubicacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.estado'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='inventario.ubicacion'),
        ),
    ]
