# Generated by Django 5.0.2 on 2025-06-27 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0004_colegio_canal_notificacion_and_more'),
        ('estudiantes', '0003_alter_estudiante_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('atraso', 'Atraso'), ('salida', 'Salida')], max_length=10)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada'), ('fallida', 'Fallida')], max_length=10)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.estudiante')),
            ],
        ),
    ]
