services:
  - type: web
    name: edumodulo
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    autoDeploy: true
    buildCommand: docker build -t edumodulo .
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
