# Generated by Django 5.0.2 on 2025-10-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrasos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atraso',
            name='con_certificado',
            field=models.BooleanField(default=False),
        ),
    ]
