# Generated by Django 5.0.2 on 2025-05-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atrasos', '0001_initial'),
        ('salidas', '0002_registroasistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atraso',
            name='registro_asistencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atraso', to='salidas.registroasistencia'),
        ),
    ]
