# Generated by Django 5.0.2 on 2025-05-25 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0003_delete_sede'),
        ('cursos', '0001_initial'),
        ('estudiantes', '0002_alter_estudiante_options_alter_estudiante_curso_and_more'),
        ('usuarios', '0005_remove_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionPrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prueba', models.CharField(max_length=255)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='colegios.colegio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='estudiantes.estudiante')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to='usuarios.perfil')),
            ],
            options={
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
