# Generated by Django 5.0.2 on 2025-05-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='asunto',
            field=models.CharField(default='chia', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10),
        ),
    ]
