# Generated by Django 5.0.2 on 2025-05-25 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegios', '0003_delete_sede'),
        ('estudiantes', '0002_alter_estudiante_options_alter_estudiante_curso_and_more'),
        ('usuarios', '0005_remove_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaAnticipada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_salida', models.DateTimeField()),
                ('notificado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_autorizadas', to='usuarios.perfil')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='colegios.colegio')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='estudiantes.estudiante')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
