# Generated by Django 5.0.2 on 2025-06-04 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_alter_salidaanticipada_estudiante_salida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalidaAnticipada',
        ),
    ]
