# Generated by Django 5.0.2 on 2025-07-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0003_delete_salidaanticipada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='justificado',
        ),
        migrations.AddField(
            model_name='salida',
            name='otros_justificativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='tipo_justificativo',
            field=models.CharField(blank=True, choices=[('', 'No justificado'), ('medico', 'Médico'), ('enfermo', 'Enfermo/a'), ('desregulacion', 'Desregulación'), ('otros', 'Otros')], max_length=20, null=True),
        ),
    ]
