# Generated by Django 5.0.2 on 2025-07-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0004_remove_salida_justificado_salida_otros_justificativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='regresado',
            field=models.BooleanField(default=False),
        ),
    ]
