# Generated by Django 5.0.2 on 2025-07-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0005_salida_regresado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tipo_justificativo',
            field=models.CharField(blank=True, choices=[('', 'No justificado'), ('Medico', 'Médico'), ('Enfermo', 'Enfermo/a'), ('Desregulacion', 'Desregulación'), ('Otros', 'Otros')], max_length=20, null=True),
        ),
    ]
