# Generated by Django 5.0.2 on 2025-07-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0006_alter_salida_tipo_justificativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='tipo_justificativo',
            field=models.CharField(blank=True, choices=[('', 'No justificado'), ('medico', 'Médico'), ('enfermo', 'Enfermo/a'), ('desregulacion', 'Desregulación'), ('otros', 'Otros')], max_length=20, null=True),
        ),
    ]
