# Generated by Django 5.0.2 on 2025-07-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0007_alter_salida_tipo_justificativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='hora_regreso',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
