# Generated by Django 5.0.2 on 2025-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfil_direccion_alter_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_acceso',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('apoderado', 'Apoderado'), ('admin_colegio', 'Administrador de Colegio'), ('soporte', 'Equipo de Soporte')], max_length=20),
        ),
    ]
