# Generated by Django 5.0.2 on 2025-05-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_nivel_acceso_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
