# Generated by Django 5.0.2 on 2025-06-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0004_colegio_canal_notificacion_and_more'),
        ('usuarios', '0006_remove_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='colegios.colegio'),
        ),
    ]
