# Generated by Django 5.0.2 on 2025-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_colegio', 'Administrador de Colegio'), ('porteria', 'Portería'), ('administrativo', 'Administrativo')], max_length=20),
        ),
    ]
