# Generated by Django 5.0.2 on 2025-08-11 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0004_colegio_canal_notificacion_and_more'),
        ('usuarios', '0008_alter_perfil_tipo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='perfil',
            name='imprimir_automaticamente',
            field=models.BooleanField(default=True, help_text='Si está marcado, se intentará imprimir automáticamente desde la web', verbose_name='Imprimir automáticamente'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='colegio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegios.colegio'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_acceso',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('admin', 'Administrador')], default='basico', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_colegio', 'Administrador de Colegio'), ('profesor', 'Profesor'), ('porteria', 'Portería'), ('superusuario', 'Superusuario')], default='profesor', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
