# Generated by Django 5.0.2 on 2025-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_perfil_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_colegio', 'Administrador de Colegio'), ('profesor', 'Profesor'), ('porteria', 'Portería'), ('superusuario', 'Superusuario'), ('administrativo', 'Administrativo')], default='profesor', max_length=20),
        ),
    ]
