# Generated by Django 5.0.2 on 2025-08-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin_colegio', 'Administrador de Colegio'), ('porteria', 'Portería'), ('superusuario', 'Superusuario'), ('administrativo', 'Administrativo')], default='porteria', max_length=20),
        ),
    ]
