# Generated by Django 5.0.2 on 2025-07-07 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_datos', models.CharField(max_length=50)),
                ('filtros_hash', models.CharField(max_length=64, unique=True)),
                ('datos', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cache de Analytics',
                'verbose_name_plural': 'Cache de Analytics',
                'indexes': [models.Index(fields=['tipo_datos', 'fecha_expiracion'], name='reportes_ca_tipo_da_aa5e6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReporteConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_reporte', models.CharField(choices=[('atrasos', 'Atrasos'), ('salidas', 'Salidas'), ('combinado', 'Combinado')], max_length=20)),
                ('filtros', models.JSONField(default=dict)),
                ('configuracion_graficos', models.JSONField(default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
            },
        ),
    ]
