# Generated by Django 5.0.2 on 2025-05-23 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='cursos.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_apoderado1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='telefono_apoderado2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
