# Generated by Django 5.0.2 on 2025-05-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegio',
            name='director',
        ),
        migrations.AddField(
            model_name='colegio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='colegio',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='colegios/logos/'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
