# Generated by Django 5.0.2 on 2025-05-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0002_remove_colegio_director_colegio_ciudad_colegio_logo_and_more'),
        ('usuarios', '0002_alter_perfil_options_rename_usuario_perfil_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
