# Generated by Django 5.0.2 on 2025-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegios', '0003_delete_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='colegio',
            name='canal_notificacion',
            field=models.CharField(choices=[('ninguno', 'Ninguno'), ('email', 'Email'), ('sms', 'SMS'), ('ambos', 'Ambos')], default='ninguno', help_text='Canal de notificación: email, sms, ambos o ninguno.', max_length=10),
        ),
        migrations.AddField(
            model_name='colegio',
            name='notificaciones_activas',
            field=models.BooleanField(default=False, help_text='¿Activar notificaciones automáticas al apoderado?'),
        ),
    ]
