# Generated by Django 5.0.2 on 2025-06-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(default='success', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'ordering': ['-created_at'],
            },
        ),
    ]
